import './globals.css'
import { Nunito } from 'next/font/google'
import Modal from './components/modal/Modal'

export const metadata = {
  title: 'AIR BNB CLONE',
  description: 'Generated by create next app',
}

import Navbar from './components/navbar/Navbar'

const font = Nunito({
  subsets: ['latin']
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Modal title="Hello Bom Next Js" isOpen/>
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
